### ISSUE TITLE
GPT prompting

### ISSUE THREAD

**Issue by akabla** [Technology-for-the-Poorest-Billion/2024-IMMI#35]
@BYGGG 
There is a statement about the prompts in the Wiki and presentation, but where can I find the detailed prompts for the project? It would be good to include them too if they are not on the repo yet.
Thanks.

**Comment by BYGGG** [comment]
@akabla The log is in this folder: https://github.com/Technology-for-the-Poorest-Billion/2024-IMMI/tree/main/final

**Comment by akabla** [comment]
Great, thanks!
